version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/omeroweb_omp_plugin"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps(pip)"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:15"
      timezone: "UTC"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps(docker)"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:30"
      timezone: "UTC"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps(docker)"
