global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: node_exporter
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets: ['loki:3100']

  - job_name: alloy
    metrics_path: /metrics
    static_configs:
      - targets: ['alloy:12345']

  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']

  - job_name: postgres_exporter
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: postgres_exporter_plugin
    static_configs:
      - targets: ['postgres-exporter-plugin:9187']

  - job_name: redis_exporter
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: blackbox_http
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://loki:3100/ready
          - http://prometheus:9090/-/ready
          - http://grafana:3000/api/health
          - http://cadvisor:8080/healthz
          - http://node-exporter:9100/metrics
          - http://postgres-exporter:9187/metrics
          - http://postgres-exporter-plugin:9187/metrics
          - http://redis-exporter:9121/metrics
          - http://omeroserver:4064
          - http://omeroweb:4090/webgateway/
          - http://alloy:12345/metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: blackbox_tcp
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
          - database:5432
          - database-plugin:5433
          - redis:6379
          - omeroserver:4064
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
